### ISSUE TITLE
Download doesn't work on iOS

### ISSUE THREAD

**Issue by schwdim** [dsgriffin/ionic-3-file-transfer-example#7] opened 2017-03-06 10:12 UTC
Hello,

I am using your app with ionic 2.2.1 and everything works just fine on Android, but `fileTransfer.download()` doesn't do anything on iOS, it just fails silently.

This issue is happening in my app where I'm using a similar method and I also tried it on yours and it neither works.

**Comment by dsgriffin** [comment] 2017-03-06 11:47
Hi @schwdim,

Are you testing on a real device? You should be hitting the error callback so I'm wondering if this issue is being caused by something else. May need to see some code otherwise

**Comment by schwdim** [comment] 2017-03-06 12:00
Right now I can only test it on an iOS emulator but I'll try as soon as I get a device. Your example app has the exact same issue, no callback at all.

**Comment by dsgriffin** [comment] 2017-03-06 12:04
@schwdim It only works on a real device due to data storage etc. Will try to make it a little more explicit in the README. Let me know how it goes!

**Comment by schwdim** [comment] 2017-03-09 13:40
Okay, so I tried on a real device, same bug... Images are not beeing downloaded and no error callback.

**Comment by schwdim** [comment] 2017-03-09 14:15
Actually FileTransfer seems to download the file but the image isn't displayed.

**Comment by dsgriffin** [comment] 2017-03-22 13:12
@schwdim It must be some other issue with your setup I guess? Let me know if you were able to get things to work. I've updated to Ionic 3 and was unable to replicate this issue, so will be closing for now. Thanks

**Closed as completed** 2017-04-13 21:54 UTC
