### ISSUE TITLE
when download for the 2nd time, it won't replace old file 

### ISSUE THREAD

**Issue by armgit5** [dsgriffin/ionic-3-file-transfer-example#16] opened 2017-07-03 10:17 UTC
I have a list of coffees and each coffee contain a url that I can download its image from firebase storage.

when I'm looping through each coffee from coffees, fileTransfer.download method downloads images fine (example of the location where the image is stored (file:///var/mobile/Containers/Data/Application/C406AEAB-1538-47FD-9FB7-79ED5D208795/Library/NoCloud/-KmAFkXiDElkR3tysdK5), but when:
1. I change the coffee images (coffee.url changes)
2. when I try to run the loop to download each coffee from coffees for the 2nd time, it downloads the new images and store them in the same location (for ex, file:///var/mobile/Containers/Data/Application/C406AEAB-1538-47FD-9FB7-79ED5D208795/Library/NoCloud/-KmAFkXiDElkR3tysdK52), but it won't display new images (instead the old images are still there). 

Please see my code here:
// Loop through all coffees to store images locally
this.coffees.forEach((coffee: Coffee) => {

    const url = coffee.url;
    const fileTransfer = this.transfer.create();
    // Start downloading image to store it locally
    fileTransfer.download(url, this.file.dataDirectory + coffee.$key)
    .then((entry) => {
      count++;
      coffee.url = entry.toURL();
      // console.log(`entry url ${entry.toURL()}`);
      // If last coffee, then save coffees in storage
      if (count == coffeesLength) {
        this.storage.set('coffees', this.coffees)
        .then(
          // Set this coffees to be the stored coffees
          storedCoffees => {
            this.coffees = storedCoffees;
          }
        )
        .catch(err => console.log(err));
      }
    })
    .catch((err => console.log(err));
});

To fix around I added keepTrack variable (please see the code below), so for the first time download, it stored in a file name file:///var/mobile/Containers/Data/Application/C406AEAB-1538-47FD-9FB7-79ED5D208795/Library/NoCloud/-KmAFkXiDElkR3tysdK51 and the second time it will be  -KmAFkXiDElkR3tysdK52 and so on... after that new images display fine on my mobile. Is there anyway to write a method that will automatically replace old files when re-download again?

let keepTrack = 1;

// Loop through all coffees to store images locally
this.coffees.forEach((coffee: Coffee) => {

    const url = coffee.url;
    const fileTransfer = this.transfer.create();
    // Start downloading image to store it locally
    fileTransfer.download(url, this.file.dataDirectory + coffee.$key + keepTrack)
    .then((entry) => {
      count++;
      coffee.url = entry.toURL();
      // console.log(`entry url ${entry.toURL()}`);
      // If last coffee, then save coffees in storage
      if (count == coffeesLength) {
        this.storage.set('coffees', this.coffees)
        .then(
          // Set this coffees to be the stored coffees
          storedCoffees => {
            this.coffees = storedCoffees;
            keepTrack++;
          }
        )
        .catch(err => console.log(err));
      }
    })
    .catch((err => console.log(err));
});

**Comment by dsgriffin** [comment] 2017-07-03 11:01
That's a caching issue I think, in which case it could be resolved by something like  

* Adding a query string to force a refresh  (e.g. `+ '&date=' + new Date().getTime()`), 
* Passing the relevant header (If-Modified-Since I think) as part of the fourth argument to download ([see here](https://ionicframework.com/docs/native/transfer/#download))

I am not sure right now what the best solution is performance-wise as obviously the more things cached the better but it depends on how often you'll be forcing each image to refresh - maybe you could save a date locally each time you download a file and then put that as the `If-Modified-Since` value so it only forces no-cache on images that have changed since?

**Comment by armgit5** [comment] 2017-07-04 03:18
thanks so much for your advice, Daniel and that makes sense now about caching. I've tried to do a pull down to refresh like 

 doRefresh(refresher) {
      this.navCtrl.setRoot(this.navCtrl.getActive().component);
      setTimeout(() => {
        console.log('Async operation has ended');
        refresher.complete();
      }, 2000);
    }

but it was still showing the **old** images still, but when I killed the application and restart the application again, **new** images showed up fine. Do you have any other suggestions other than killing the application and restart again to clear up caching? or how I could force refresh to clear up the cache properly?

**Comment by dsgriffin** [comment] 2017-07-04 08:54
I think you need to specifically force removing the cached images themselves rather than that; the solutions I mentioned above should work (either adding `+ '&date=' + new Date().getTime())` to the end of each file name when calling download, or passing in a 4th arguement to download and passing in the If-Modified-Since header, then checking on download and it will force a cache refresh on those images

**Comment by dsgriffin** [comment] 2017-07-04 21:03
Try replacing `keepTrack` with a query string, so just

```
fileTransfer.download(url, this.file.dataDirectory + coffee.$key + '&date=' + new Date().getTime())
```

**Comment by armgit5** [comment] 2017-07-05 03:20
Thank you for your comment :-) if I download new image files with new dates, would you recommend to delete old image files with old dates first? is there any ionic 2 method to see all of the files that have been previously downloaded and not currently used.

**Comment by dsgriffin** [comment] 2017-07-05 09:04
I'm sure you should be able to write to the same files each time and display content instantly actually, but I don't have any way to reproduce what you have locally here :/ You can use the [`File`](https://ionicframework.com/docs/native/file/)  module with methods like `checkDir`, `checkFile` and `removeRecursively` to go through and delete. 

You may also want to ask this question on the [Ionic Forums](https://forum.ionicframework.com) as sometimes devs from the Ionic Native team answer questions on there and can hopefully provide a more perfect answer

**Closed as completed** 2018-08-05 19:03 UTC
